<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RegistrosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('registros')->delete();
        
        \DB::table('registros')->insert(array (
            0 => 
            array (
                'id' => 1,
                'id_empresa' => 1,
                'email' => 'tesyjoju@mailinator.co',
                'fecha_inicio' => '2022-08-24 17:08:21',
                'token' => '5ilanhte-zh14-j3oj-vk3t-6kboarjpurc',
                'sexo' => 'Femenino',
                'estado_civil' => 'Divorciado',
                'edad' => '31-35 años',
                'antiguedad' => '11-15 años',
                'estudios' => 'Tec. Superior',
                'area' => 'Necessitatibus exped',
                'tipo_contratacion' => 'Accusamus quod omnis',
                'jornada_trabajo' => 'Ad nobis expedita re',
                'jornada_trabajo_opcional' => NULL,
                'rotacion_turnos' => 'Blanditiis maxime au',
                'tipo_empleado' => 'Quis quaerat sint ni',
                'experiencia_laboral' => 'Menos de 1 año',
                'item_1' => 4,
                'item_2' => 0,
                'item_3' => 2,
                'item_4' => 1,
                'item_5' => 1,
                'item_6' => 2,
                'item_7' => 4,
                'item_8' => 1,
                'item_9' => 4,
                'item_10' => 1,
                'item_11' => 0,
                'item_12' => 1,
                'item_13' => 4,
                'item_14' => 1,
                'item_15' => 4,
                'item_16' => 2,
                'item_17' => 1,
                'item_18' => 4,
                'item_19' => 4,
                'item_20' => 1,
                'item_21' => 1,
                'item_22' => 2,
                'item_23' => 1,
                'item_24' => 1,
                'item_25' => 1,
                'item_26' => 4,
                'item_27' => 1,
                'item_28' => 0,
                'item_29' => 0,
                'item_30' => 1,
                'item_31' => 2,
                'item_32' => 2,
                'item_33' => 1,
                'item_34' => 4,
                'item_35' => 2,
                'item_36' => 4,
                'item_37' => 2,
                'item_38' => 3,
                'item_39' => 1,
                'item_40' => 1,
                'item_41' => 1,
                'item_42' => 3,
                'item_43' => 3,
                'item_44' => 0,
                'item_45' => 4,
                'item_46' => 0,
                'item_47' => 4,
                'item_48' => 0,
                'item_49' => 2,
                'item_50' => 4,
                'item_51' => 0,
                'item_52' => 0,
                'item_53' => 3,
                'item_54' => 4,
                'item_55' => 3,
                'item_56' => 3,
                'item_57' => 4,
                'item_58' => 4,
                'item_59' => 0,
                'item_60' => 1,
                'item_61' => 2,
                'item_62' => 3,
                'item_63' => 1,
                'item_64' => 2,
                'item_65' => 0,
                'item_66' => 0,
                'item_67' => 0,
                'item_68' => 0,
                'item_69' => 0,
                'item_70' => 0,
                'item_71' => 0,
                'item_72' => 0,
                'item_sc' => 'No',
                'item_jefe' => 'No',
                'ets_1' => NULL,
                'ets_2' => NULL,
                'ets_3' => NULL,
                'ets_4' => NULL,
                'ets_5' => NULL,
                'ets_6' => NULL,
                'ets_7' => NULL,
                'ets_8' => NULL,
                'ets_9' => NULL,
                'ets_10' => NULL,
                'ets_11' => NULL,
                'ets_12' => NULL,
                'ets_13' => NULL,
                'ets_14' => NULL,
                'ets_15' => NULL,
                'ets_16' => NULL,
                'ets_17' => NULL,
                'ets_18' => NULL,
                'ets_19' => NULL,
                'ets_20' => NULL,
                'created_at' => '2022-08-24 17:09:07',
                'updated_at' => '2022-08-24 17:09:07',
            ),
            1 => 
            array (
                'id' => 2,
                'id_empresa' => 1,
                'email' => 'tesyjoju@mailinator.com',
                'fecha_inicio' => '2022-08-24 17:08:21',
                'token' => 'mfvzjylm-4h8s-3vkx-n9q7-pvpzxhg5njq',
                'sexo' => 'Femenino',
                'estado_civil' => 'Divorciado',
                'edad' => '31-35 años',
                'antiguedad' => '11-15 años',
                'estudios' => 'Tec. Superior',
                'area' => 'Necessitatibus exped',
                'tipo_contratacion' => 'Accusamus quod omnis',
                'jornada_trabajo' => 'Ad nobis expedita re',
                'jornada_trabajo_opcional' => NULL,
                'rotacion_turnos' => 'Blanditiis maxime au',
                'tipo_empleado' => 'Quis quaerat sint ni',
                'experiencia_laboral' => 'Menos de 1 año',
                'item_1' => 4,
                'item_2' => 0,
                'item_3' => 2,
                'item_4' => 1,
                'item_5' => 1,
                'item_6' => 2,
                'item_7' => 4,
                'item_8' => 1,
                'item_9' => 4,
                'item_10' => 1,
                'item_11' => 0,
                'item_12' => 1,
                'item_13' => 4,
                'item_14' => 1,
                'item_15' => 4,
                'item_16' => 2,
                'item_17' => 1,
                'item_18' => 4,
                'item_19' => 4,
                'item_20' => 1,
                'item_21' => 1,
                'item_22' => 2,
                'item_23' => 1,
                'item_24' => 1,
                'item_25' => 1,
                'item_26' => 4,
                'item_27' => 1,
                'item_28' => 0,
                'item_29' => 0,
                'item_30' => 1,
                'item_31' => 2,
                'item_32' => 2,
                'item_33' => 1,
                'item_34' => 4,
                'item_35' => 2,
                'item_36' => 4,
                'item_37' => 2,
                'item_38' => 3,
                'item_39' => 1,
                'item_40' => 1,
                'item_41' => 1,
                'item_42' => 3,
                'item_43' => 3,
                'item_44' => 0,
                'item_45' => 4,
                'item_46' => 0,
                'item_47' => 4,
                'item_48' => 0,
                'item_49' => 2,
                'item_50' => 4,
                'item_51' => 0,
                'item_52' => 0,
                'item_53' => 3,
                'item_54' => 4,
                'item_55' => 3,
                'item_56' => 3,
                'item_57' => 4,
                'item_58' => 4,
                'item_59' => 0,
                'item_60' => 1,
                'item_61' => 2,
                'item_62' => 3,
                'item_63' => 1,
                'item_64' => 2,
                'item_65' => 0,
                'item_66' => 0,
                'item_67' => 0,
                'item_68' => 0,
                'item_69' => 2,
                'item_70' => 4,
                'item_71' => 4,
                'item_72' => 2,
                'item_sc' => 'Sí',
                'item_jefe' => 'Sí',
                'ets_1' => 'Sí',
                'ets_2' => 'No',
                'ets_3' => 'No',
                'ets_4' => 'Sí',
                'ets_5' => 'No',
                'ets_6' => 'Sí',
                'ets_7' => 'No',
                'ets_8' => 'No',
                'ets_9' => 'Sí',
                'ets_10' => 'No',
                'ets_11' => 'Sí',
                'ets_12' => 'No',
                'ets_13' => 'Sí',
                'ets_14' => 'No',
                'ets_15' => 'No',
                'ets_16' => 'No',
                'ets_17' => 'No',
                'ets_18' => 'Sí',
                'ets_19' => 'Sí',
                'ets_20' => 'Sí',
                'created_at' => '2022-08-24 17:09:49',
                'updated_at' => '2022-08-24 17:09:49',
            ),
        ));
        
        
    }
}